### ISSUE TITLE
Embedded JavaScript questions

### ISSUE THREAD

**Issue by Magnogen** [TodePond/MotherTode#22]
So I noticed [in notes.txt on line 70 - 71](https://github.com/TodePond/MotherTode/blob/0b3b74cbcf129d5dbd2844b0164e9d6ea81d9a1b/notes.txt#L70), that there seems to be js's arrow function syntax.

Is that an _actual_ js function? If so, will any javascript there work? If not (which would make sense from the `|` instead of `||`) why use syntax that's similar to js, when you can use keywords like `and`/`or` and a syntax that's similar to what you've already done with the basic structure of MotherTode, namely:

```
let either = (a, b) {
    try {
        match a
    } else {
        match b
    }
}
either("foo", "bar")
```

Not sure if the `try` thing works, it's up to you, I was trying to make it more side-effecty, instead of returning values, which is similar to how `match`, `throw`, `let` and `term` work. (at least from what I can see)

If you don't like the `try`, then this'd probably work instead.

```
let either = (a, b) {
    match a or b
}
either("foo", "bar")
```

Loving the notes, very interesting!

Oh and another suggestion: Make MotherTode with MotherTode!

**Comment by TodePond** [comment]
Hey so line 70 isn't javascript - it's a mothertode function. The notes.txt file was just some jottings, the full docs are here: https://todepond.gitbook.io/mothertode

You might need to reload the page's cache to get the updated version.

And the explanation of mothertode functions is here: https://todepond.gitbook.io/mothertode/functions

The reason it uses `|` is because it's based on EBNF:
https://en.m.wikipedia.org/wiki/Extended_Backus%E2%80%93Naur_form

Oh and I'll make it in mothertode eventually, when it's stable enough :)

**Comment by Magnogen** [comment]
Oooo interesting! I'll take a look at those, thanks!

Ah yes, EBNF finds its way everywhere 😂
